### ISSUE TITLE
Display with i2s "backpack"

### ISSUE THREAD

**Issue by probonopd** [AnotherJohnH/picoX7#5]
It would be nice if we could use a display module with a i2s "backpack" so that we have to wire up only 4 wires for the display instead of many.

![image](https://github.com/AnotherJohnH/picoX7/assets/2480569/01a21771-7d9e-4492-b399-ce03eea1083e)

**Comment by AnotherJohnH** [comment]
Agree that would be nicer.

Have recently added I2C support to the SDK "Platform". Having quickly looked up an I2C 16x2 LCD can see that, unsurprsingly, the internal register set looks the same as the parallel LCD devices. So the work would be...

1.  Write a new version of [MTL/Lcd.h](https://github.com/AnotherJohnH/Platform/blob/a5334979c00c0b1448b7ad0d50a105444d258198/MTL/Lcd.h) ripping out the raw GPIO use and putting in an instance of MTL::I2C [MTL/rp2040/I2C.h](https://github.com/AnotherJohnH/Platform/blob/a5334979c00c0b1448b7ad0d50a105444d258198/MTL/chip/rp2040/I2C.h) 
2. Add another hardware target to the build with some conditional compilation in [picoX7.cpp](https://github.com/AnotherJohnH/picoX7/blob/main/Source/picoX7.cpp) to select the I2C LCD driver.

Might buy one to play with when I next order some bits.

**Comment by AnotherJohnH** [comment]
Have completed the trivial parts here [721a3eb](https://github.com/AnotherJohnH/picoX7/commit/721a3eb9524ba64c57f75a8670e3a4f91ae0ac6d) 
Remaining work is to complete implementation of [Platform/MTL/AlphaNumLcd_I2C.h](https://github.com/AnotherJohnH/Platform/blob/master/MTL/AlphaNumLcd_I2C.h)

**Comment by AnotherJohnH** [comment]
Support completed. Works for me with an AiP31068L based I2C 16x2 LCD from Waveshare via the I2C1 on pins 19 and 20. Thankyou for the suggestion that's a nice improvement. See the latest release [v0.18](https://github.com/AnotherJohnH/picoX7/releases/tag/v0.18)

**Comment by AnotherJohnH** [comment]
Support completed. Works for me with an AiP31068L based I2C 16x2 LCD from Waveshare via the I2C1 on pins 19 and 20. Thankyou for the suggestion that's a nice improvement. See the latest release [v0.18](https://github.com/AnotherJohnH/picoX7/releases/tag/v0.18)

**Comment by probonopd** [comment]
Which address does your display use?

**Comment by AnotherJohnH** [comment]
See Platform/MTL/AlphaNumLcd_I2C.h. The address is passed as the only argument to the display driver constructor. But has a default value that matches the display I use which is 0x3E. This values is masked with 0x7F and written unshifted into the RP I2C peripherals IC_TAR (target address) register. So if you need a different address add { <addr } to the instantiation of the LCD driver in picoX7.cpp e.g.

```
static MTL::AlphaNumLcd<MTL::I2C1_P19_P20,
                        /* COLS */ 16,
                        /* ROWS */ 2> lcd { 0xHH };
```

I notice in the official SDK that similar devices use an address of 0x27 so that might be worth trying.  Maybe the device I have, a "Waveshare LCD 1602 I2C" is unusual. To be honest I struggled to find this rather important information for the display I have, on either the PiHut or Waveshare web pages. Until eventually I saw this line in a micro python example they published ...

```
#Device I2C Arress
LCD_ADDRESS  = (0x7C>>1)
```

Which, obviously, is a rather cryptic way of writing 0x3E.

**Comment by AnotherJohnH** [comment]
... will post a patch making the I2C address clearer in picoX7.cpp

**Comment by AnotherJohnH** [comment]
... see https://github.com/AnotherJohnH/picoX7/commit/d2f77267cb0e3e65a20598f3285e89cd395b69f4

**Comment by probonopd** [comment]
Thanks @AnotherJohnH. Indeed all the generic displays I have use 0x27, so I will try that.

**Comment by probonopd** [comment]
All that really happens now is that the backlight on the display (the one from the original post) gets switched off, around the time when `# 001 NAME BRASS   1  ALG 22 FBK 7 SYNC on  PMS 3 TRN 0` appears on the serial console:

```
Program  : picoX7 (WaveShare Rev2.1 I2C LCD)
Author   : Copyright (c) 2023 John D. Haughton
Version  : 0.18
Commit   : 2a2902ada41b07839b052e695fa4de73233b510b
Built    : 07:49:14 Sep 30 2024
Compiler : 9.2.1 20191025 (release) [ARM/arm-9-branch revision 277599]

# 001 NAME BRASS   1  ALG 22 FBK 7 SYNC on  PMS 3 TRN 0
LFO WAV sin SPD 37 DLY 00 PMD 05 AMD 00 SYNC off
OP AMS FREQ    DET R1 R2 R3 R4  L1 L2 L3 L4  BPT   CURVE    DEPTH RTE OUT KVS
6   0  R  1.00  0  49 99 28 68  98 98 91 00  39  -exp -exp  54 50  4   82  2
5   0  R  1.00  1  77 36 41 71  99 98 98 00  39  +lin +lin  00 00  0   98  2
4   0  R  1.00  0  77 36 41 71  99 98 98 00  39  +lin +lin  00 00  0   99  2
3   0  R  1.00 -2  77 76 82 71  99 98 98 00  39  +lin +lin  00 00  0   99  2
2   0  R  0.50  7  62 51 29 71  82 95 96 00  27  +lin -exp  00 07  0   86  0
1   0  R  0.50  7  72 76 99 71  99 88 96 00  39  +lin +lin  00 14  0   98  0
PITCH EG           84 95 95 60  50 50 50 50
```

**Comment by AnotherJohnH** [comment]
Ugg :-( I guess that means the I2C address is working but the I2C interface in the Waveshare device I have is not the same as the "generic displays" that usually live at 0x27. Will dig into this a bit further when I get a chance. Do you know the part number of the I2C device on your display?

**Comment by probonopd** [comment]
I think they are all using various [8574](https://www.ti.com/lit/ds/symlink/pcf8574.pdf) compatible chips. Mine says "8574T".

**Comment by AnotherJohnH** [comment]
So seems there are (at least) two types of I2C 16x2 LCD....

1. The one you have uses a generic I2C bridge chip (the PCF8574) to drive the parallel interface to the old style HD44780 LCD display driver. I guess back-pack was the clue I missed. [I2C 16x2 Arduino LCD display module](https://thepihut.com/products/i2c-16x2-arduino-lcd-display-module)
2. The device I have, which uses an all in one I2C LCD driver chip.  [LCD 1602 I2C module](https://thepihut.com/products/lcd1602-i2c-module)

**Comment by probonopd** [comment]
Could it be that you forgot to push Platform d6af84a04098e0b8219930b8238eb8fdf3f17c61? I am currently getting

```
Fetching submodules
  /usr/bin/git submodule sync
  /usr/bin/git -c protocol.version=2 submodule update --init --force
  Submodule 'Platform' (https://github.com/AnotherJohnH/Platform.git) registered for path 'Platform'
  Cloning into '/home/runner/work/picoX7/picoX7/Platform'...
  Error: fatal: remote error: upload-pack: not our ref d6af84a04098e0b8219930b8238eb8fdf3f17c61
  Error: fatal: Fetched in submodule path 'Platform', but it did not contain d6af84a04098e0b8219930b8238eb8fdf3f17c61. Direct fetching of that commit failed.
  Error: The process '/usr/bin/git' failed with exit code 128
```

This kind of error could be caught easily if continuous integration would be merged:

* https://github.com/AnotherJohnH/picoX7/pull/9

**Comment by AnotherJohnH** [comment]
Oh, sorry about that have pushed the missing Platform patch.

**Comment by probonopd** [comment]
Moving in the right direction, but not quite yet there.

When I power cycle the display, I immediately see a blinking square over a _ character. Then the screen shows the string "NTERND" followed by blanks, and the blinking square over a _ character is in the 4th from the right on the second line.

I would not be entirely surprised if some "waits" were missing, or something small along those lines.

**Comment by AnotherJohnH** [comment]
After a reset the display should be....
```
*    picoX7    *
*  SYNTHESIZER *
```
and then after 2.5 seconds...
```
INTERNAL VOICE
INT 1 BRASS   1
```
so yep, seems close. I'll double check the code and the timings in particular.

**Comment by AnotherJohnH** [comment]
Guessing it's got through the initialisation ok-ish.  So the general byte send code is possibly the broken part.

I'd copied the delays that I'd used in the parallel version of the driver which are (setup) 10us and (hold) 38us. The Python you linked had no delays in this area, but then Python is going to be so slow that it probably covers the requirement without trying. Looking at the C in the official pico-example can see some massive 600us delays and also the code takes time to setup the data nibble before asserting the E pin, again with a 600us delay.

The data sheet does not support the need to setup the data before asserting E, it is clear that the data is captured on the falling edge of E, which makes me suspicious of the 600us too. TBH to follow the data sheet all these drivers (mine included) should be sampling the busy flag pin instead of delays. Which I guess us coders are too lazy to do!

Have posted a [patch](https://github.com/AnotherJohnH/picoX7/commit/39e6b5d68a0a7fa364d3d5b94330636c6465c3b7) which updates the timings to 600us. If I was able to test would have tuned this down until it was just working and then doubled it.

**Comment by probonopd** [comment]
Sorry to be a pain, but now I get strange special characters on the screen. I do see that the display content changes after 2.5 seconds (so it's alive), but unfortunately nothing is readable. The characters being shown seem to be entirely reproducible across reboots. 

If you can give me instructions on what to change/test, I can do it.
